spring.application.name=cashiq-backend
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
spring.datasource.username=RM561990
spring.datasource.password=241106
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

app.version=00.03.00